# ==============================
# Matugen Kitty Theme
# ==============================

background #14140c
foreground #e6e2d5

cursor #ceca75
cursor_text_color #343200

selection_background #4b4900
selection_foreground #ebe68e

url_color #a5d0bb

# ANSI
color0 #14140c
color1 #ffb4ab
color2 #a5d0bb
color3 #cbc8a4
color4 #ceca75
color5 #cbc8a4
color6 #a5d0bb
color7 #e6e2d5

color8 #49473a
color9 #ffb4ab
color10 #a5d0bb
color11 #cbc8a4
color12 #ceca75
color13 #cbc8a4
color14 #a5d0bb
color15 #e6e2d5

