-- Generated by Matugen
-- DO NOT EDIT MANUALLY

local M = {}

M.background = "{{ colors.surface.default.hex }}"
M.foreground = "{{ colors.on_surface.default.hex }}"

M.primary = "{{ colors.primary.default.hex }}"
M.on_primary = "{{ colors.on_primary.default.hex }}"

M.primary_container = "{{ colors.primary_container.default.hex }}"
M.on_primary_container = "{{ colors.on_primary_container.default.hex }}"

M.secondary = "{{ colors.secondary.default.hex }}"
M.on_secondary = "{{ colors.on_secondary.default.hex }}"

M.secondary_container = "{{ colors.secondary_container.default.hex }}"
M.on_secondary_container = "{{ colors.on_secondary_container.default.hex }}"

M.tertiary = "{{ colors.tertiary.default.hex }}"
M.on_tertiary = "{{ colors.on_tertiary.default.hex }}"

M.error = "{{ colors.error.default.hex }}"
M.on_error = "{{ colors.on_error.default.hex }}"

M.surface = "{{ colors.surface.default.hex }}"
M.surface_variant = "{{ colors.surface_variant.default.hex }}"

M.outline = "{{ colors.outline.default.hex }}"
M.outline_variant = "{{ colors.outline_variant.default.hex }}"

M.primary_fixed = "{{ colors.primary_fixed.default.hex }}"
M.primary_fixed_dim = "{{ colors.primary_fixed_dim.default.hex }}"
M.secondary_fixed = "{{ colors.secondary_fixed.default.hex }}"
M.secondary_fixed_dim = "{{ colors.secondary_fixed_dim.default.hex }}"
M.tertiary_fixed = "{{ colors.tertiary_fixed.default.hex }}"
M.tertiary_fixed_dim = "{{ colors.tertiary_fixed_dim.default.hex }}"

return M
